src/Entity/Profile.php
<?php

namespace Drupal\friggeri_cv\Entity;

use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\friggeri_cv\ProfileInterface;

/**
 * Defines the profile entity class.
 *
 * @ContentEntityType(
 *   id = "profile",
 *   label = @Translation("Profile"),
 *   label_collection = @Translation("Profiles"),
 *   handlers = {
 *     "view_builder" = "Drupal\Core\Entity\EntityViewBuilder",
 *     "list_builder" = "Drupal\friggeri_cv\ProfileListBuilder",
 *     "views_data" = "Drupal\views\EntityViewsData",
 *     "access" = "Drupal\friggeri_cv\ProfileAccessControlHandler",
 *     "form" = {
 *       "add" = "Drupal\friggeri_cv\Form\ProfileForm",
 *       "edit" = "Drupal\friggeri_cv\Form\ProfileForm",
 *       "delete" = "Drupal\Core\Entity\ContentEntityDeleteForm"
 *     },
 *     "route_provider" = {
 *       "html" = "Drupal\Core\Entity\Routing\AdminHtmlRouteProvider",
 *     }
 *   },
 *   base_table = "profile",
 *   data_table = "profile_field_data",
 *   translatable = TRUE,
 *   admin_permission = "access profile overview",
 *   entity_keys = {
 *     "id" = "id",
 *     "langcode" = "langcode",
 *     "label" = "name",
 *     "uuid" = "uuid"
 *   },
 *   links = {
 *     "add-form" = "/admin/profile/add",
 *     "canonical" = "/friggeri-cv/profile/{profile}",
 *     "edit-form" = "/admin/profile/{profile}/edit",
 *     "delete-form" = "/admin/profile/{profile}/delete",
 *     "collection" = "/admin/profiles"
 *   },
 * )
 */
class Profile extends ContentEntityBase implements ProfileInterface {

  /**
   * {@inheritdoc}
   */
  public function getName() {
    return $this->get("name")->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setName($name) {
    $this->set("name", $name);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getTitle() {
    return $this->get("title")->value;
  }

  /**
   * {@inheritdoc}
   */
  public function setTitle($name) {
    $this->set("title", $name);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getDefaultPicture() {
    $img = base_path() . drupal_get_path("module", "friggeri_cv")
      . "/img/person.svg";
    return [
      "data" => [
        "#markup" => "<img src='$img'>",
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getPicture() {
    $media = $this->picture->entity;
    if (isset($media)) {
      $image = $media->field_media_image->entity;
      if (isset($image)) {
        return [
          "data" => [
            '#theme' => 'image_style',
            '#style_name' => 'thumbnail',
            '#uri' => $image->getFileUri(),
          ],
        ];
      }
    }

    return $this->getDefaultPicture();
  }

  /**
   * {@inheritdoc}
   */
  public function getSections() {
    return $this->get('sections')->referencedEntities();
  }

  /**
   * {@inheritdoc}
   */
  public static function preDelete(EntityStorageInterface $storage, array $entities) {
    parent::preDelete($storage, $entities);
    foreach ($entities as $entity) {
      foreach ($entity->getSections() as $section) {
        $section->delete();
      }
      foreach ($entity->get('footer_col_1_items')->referencedEntities() as $item) {
        $item->delete();
      }
      foreach ($entity->get('footer_col_2_items')->referencedEntities() as $item) {
        $item->delete();
      }
    }
  }

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {

    $fields = parent::baseFieldDefinitions($entity_type);

    $fields['name'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Name'))
      ->setDescription(new TranslatableMarkup('The profile name'))
      ->setTranslatable(TRUE)
      ->setRequired(TRUE)
      ->setSetting('max_length', 255)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'string',
      ])
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'settings' => [
          'placeholder' => "John SMITH",
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    $fields['title'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Title'))
      ->setDescription(new TranslatableMarkup('The professional title'))
      ->setTranslatable(TRUE)
      ->setRequired(FALSE)
      ->setSetting('max_length', 255)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'string',
      ])
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'settings' => [
          'placeholder' => "Goldsmith",
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    $fields['picture'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(new TranslatableMarkup('Picture'))
      ->setDescription(new TranslatableMarkup('The profile picture'))
      ->setRequired(FALSE)
      ->setSetting('target_type', 'media')
      ->setSetting('handler', 'default:media')
      ->setSettings([
        'handler_settings' => [
          'target_bundles' => [
            'image' => 'image',
          ],
        ],
      ])
      ->setCardinality(1)
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'media_library_widget',
        'weight' => 3,
      ])
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'media_thumbnail',
        'settings' => [
          'image_style' => 'thumbnail',
        ],
      ]);

    $fields['contact_box'] = BaseFieldDefinition::create('friggeri_cv_profile_contact_box')
      ->setLabel(new TranslatableMarkup('Sidebar Items'))
      ->setTranslatable(TRUE)
      ->setRequired(FALSE)
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setDisplayOptions('form', [
        'type' => 'friggeri_cv_profile_contact_box_default',
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['sections'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(new TranslatableMarkup('Sections'))
      ->setTranslatable(TRUE)
      ->setRequired(FALSE)
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setSetting('target_type', 'profile_section')
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'inline_entity_form_complex',
      ]);

    // Footer.
    $fields['footer_col_1_title'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Title'))
      ->setDescription(new TranslatableMarkup('The title of the list'))
      ->setSetting('max_length', 255)
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'settings' => [
          'placeholder' => "ex. Languages",
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'string',
      ])
      ->setDisplayConfigurable('view', TRUE);

    $fields['footer_col_1_title_color'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Title color'))
      ->setSetting('max_length', 255)
      ->setDisplayOptions('form', [
        'type' => 'color_picker',
        'settings' => [
          'default_color' => "#ac0707",
        ],
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['footer_col_1_colored_letter_number'] = BaseFieldDefinition::create('integer')
      ->setLabel(new TranslatableMarkup('# of colored letters'))
      ->setSettings(['min' => 0, 'max' => 25])
      ->setDefaultValue(3)
      ->setDisplayOptions('form', [
        'type' => 'number',
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['footer_col_1_items'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(new TranslatableMarkup('Items'))
      ->setTranslatable(TRUE)
      ->setRequired(FALSE)
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setSetting('target_type', 'profile_footer_item')
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'inline_entity_form_complex',
      ]);

    $fields['footer_col_2_title'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Title'))
      ->setDescription(new TranslatableMarkup('The title of the list'))
      ->setSetting('max_length', 255)
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'settings' => [
          'placeholder' => "ex. Hobbies",
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'string',
      ])
      ->setDisplayConfigurable('view', TRUE);

    $fields['footer_col_2_title_color'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Title color'))
      ->setSetting('max_length', 255)
      ->setDisplayOptions('form', [
        'type' => 'color_picker',
        'settings' => [
          'default_color' => "#ac0707",
        ],
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['footer_col_2_colored_letter_number'] = BaseFieldDefinition::create('integer')
      ->setLabel(new TranslatableMarkup('# of colored letters'))
      ->setSettings(['min' => 0, 'max' => 25])
      ->setDefaultValue(3)
      ->setDisplayOptions('form', [
        'type' => 'number',
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['footer_col_2_items'] = BaseFieldDefinition::create('entity_reference')

templates/aside.html.twig
<section>
    {{ picture }}
</section>

{% for box in profile.contact_box %}
    <section>
        <h5>{{ box.heading | raw }}</h5>
        <div class="contact-box">
            <i class="{{ box.font_awesome_icon }}"></i>
            <div>
                {{ box.contacts | raw }}
            </div>
        </div>
    </section>
{% endfor %}

templates/footer.html.twig
{% set title1  = profile.footer_col_1_title.value %}
{% set color1  = profile.footer_col_1_title_color.value %}
{% set number1 = profile.footer_col_1_colored_letter_number.value %}
{% set title2  = profile.footer_col_2_title.value %}
{% set color2  = profile.footer_col_2_title_color.value %}
{% set number2 = profile.footer_col_2_colored_letter_number.value %}
<section>
  <div class="container">
    <div class="row">
      <div class="column">
        <h4><span style="color: {{ color1 }}">{{ title1[:number1] }}</span>{{ title1[number1:] }}</h4>
        <ul>
          {% for item in profile.footer_col_1_items %}
            <li>
              {% if item.entity.picture.entity.field_media_image.entity.uri.value %}
                {%
                  set icon = {
                    '#theme': 'image',
                    '#uri': item.entity.picture.entity.field_media_image.entity.uri.value,
                    '#alt': item.entity.picture.entity.field_media_image.alt
                  }
                %}
                {{ icon }}
              {% endif %}
              {{ item.entity.text.value }}
            </li>
          {% endfor %}
        </ul>
      </div>
      <div class="column">
        <h4><span style="color: {{ color2 }}">{{ title2[:number2] }}</span>{{ title2[number2:] }}</h4>
        <ul>
          {% for item in profile.footer_col_2_items %}
            <li>
              {% if item.entity.picture.entity.field_media_image.entity.uri.value %}
                {%
                  set icon = {
                    '#theme': 'image',
                    '#uri': item.entity.picture.entity.field_media_image.entity.uri.value,
                    '#alt': item.entity.picture.entity.field_media_image.alt
                  }
                %}
                {{ icon }}
              {% endif %}
              {{ item.entity.text.value }}
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</section>

templates/header.html.twig
<header class="header">
    <h1>{{ profile.name.value | raw }}</h1>
    <div class="sub">{{ profile.title.value | raw }}</div>
</header>

templates/horizontal-tabs.html.twig
{#
/**
 * @file
 * Default theme implementation for horizontal tabs.
 *
 * Available variables
 * - attributes: A list of HTML attributes for the wrapper element.
 * - children: The rendered tabs.
 *
 * @see template_preprocess_horizontal_tabs()
 *
 * @ingroup themeable
 */
#}
<div{{ attributes.setAttribute('data-horizontal-tabs-panes', TRUE) }}>{{ children }}</div>

templates/html--friggeri-cv.html.twig
{#
/**
 * @file
 * Theme override for the basic structure of a single Drupal page.
 *
 * Variables:
 * - logged_in: A flag indicating if user is logged in.
 * - root_path: The root path of the current page (e.g., node, admin, user).
 * - node_type: The content type for the current node, if the page is a node.
 * - head_title: List of text elements that make up the head_title variable.
 *   May contain one or more of the following:
 *   - title: The title of the page.
 *   - name: The name of the site.
 *   - slogan: The slogan of the site.
 * - page_top: Initial rendered markup. This should be printed before 'page'.
 * - page: The rendered page markup.
 * - page_bottom: Closing rendered markup. This variable should be printed after
 *   'page'.
 * - db_offline: A flag indicating if the database is offline.
 * - placeholder_token: The token for generating head, css, js and js-bottom
 *   placeholders.
 *
 * @see template_preprocess_html()
 */
#}
{%
  set body_classes = [
    logged_in ? 'user-logged-in',
    not root_path ? 'path-frontpage' : 'path-' ~ root_path|clean_class,
    node_type ? 'page-node-type-' ~ node_type|clean_class,
    db_offline ? 'db-offline',
  ]
%}
<!DOCTYPE html>
<html{{ html_attributes }}>
  <head>
    <head-placeholder token="{{ placeholder_token }}">
    <title>{{ head_title|safe_join(' | ') }}</title>
    <css-placeholder token="{{ placeholder_token }}">
    <js-placeholder token="{{ placeholder_token }}">
  </head>
  <body{{ attributes.addClass(body_classes) }}>
    {{ page_top }}
    {{ page }}
    {{ page_bottom }}
    <js-bottom-placeholder token="{{ placeholder_token }}">
  </body>
</html>

templates/main.html.twig
{% for section in profile.sections %}
    {% set s = section.entity %}
    {% set color = s.title_color.value %}
    {% set number = s.colored_letter_number.value %}
    <section>
        <h4><span style="color: {{ color }}">{{ s.title.value[:number] }}</span>{{ s.title.value[number:] }}</h4>
        {% for entity_box in s.entity_box  %}
            <div class="entity-box">
                <div class="row">
                    <div class="col-xs-3">
                        <div class="tenure">
                            {{ entity_box.value.tenure | raw }}
                        </div>
                    </div>
                    <div class="col-xs-9">
                        <div class="entity-title">
                            <div class="entity-name">
                                {{ entity_box.value.title | raw }}
                            </div>
                            <div class="authority-name-loc">
                                {{ entity_box.value.employer | raw }}
                            </div>
                        </div>
                        <div class="entity-position">
                            {{ entity_box.value.domain | raw }}
                        </div>
                        <div class="entity-info">
                            {{ entity_box.value.info | raw }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>
{% endfor %}

templates/profile.html.twig
{% set uri = profile.picture.entity.field_media_image.entity.uri.value %}
{% if uri is null %}
  {% set picture = profile.defaultPicture %}
{% else %}
  {%
    set picture = {
      '#theme': 'image',
      '#uri': uri,
    }
  %}
{% endif %}
{% set module_path = _self|split("/templates")|first %}
{% include '@friggeri_cv/header.html.twig' %}

<div class="row">
  <div class="col-xs-3">
    <aside>{% include '@friggeri_cv/aside.html.twig' %}</aside>
  </div>
  <div class="col-xs-9">
    <main>
      {% include '@friggeri_cv/main.html.twig' %}
      {% include '@friggeri_cv/footer.html.twig' %}
    </main>
  </div>
</div>